language: objective-c
osx_image: xcode8
cache: 
  - cocoapods
env:
  global:
    - WORKSPACE="Wunderfull.xcworkspace"
    - IOS_FRAMEWORK_SCHEME="Wunderfull"
    - IOS_SDK=iphonesimulator10.0
matrix:
  include:
    - osx_image: xcode8
      env: DESTINATION="OS=10.0,name=iPhone 5S"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
    - osx_image: xcode8
      env: DESTINATION="OS=10.0,name=iPhone 6S"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
    - osx_image: xcode8
      env: DESTINATION="OS=10.0,name=iPhone 7"      SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
before_install:
   # Pre-Release version of Cocoapods needed for Xcode8 environment.
  - gem install cocoapods --pre # Since Travis is not always on latest version
  - pod install --repo-update
script:
  - set -o pipefail 
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi